### ISSUE TITLE
Suggestion - config delay before respawning

### ISSUE THREAD

**Issue by MLMII** [henkelmax/better-respawn#1]
I have the configs set to basically disable bedspawns and for relatively long respawn teleports in order to make death a little more punishing (plus I use it to spread people out away from spawn by killing them the first time they log in); but something that I noticed when in LAN is that people have the temptation to spam kill themselves hoping to respawn closer to where they want to end up.

I attempted to use "Respawn Delay"  https://www.curseforge.com/minecraft/mc-mods/respawn-delay  in order to combat this temptation but that mod conflicts with yours as I don't believe it triggers actual death upon dying.

Thank you for your time,

**Comment by henkelmax** [comment]
Thanks for this suggestion. The version should be up on curseforge in a few minutes.
