### ISSUE TITLE
[1.18.2] Spawned at spawn point instead (still)

### ISSUE THREAD

**Issue by Proxwian** [henkelmax/better-respawn#10]
**Please read the [FAQ](https://modrepo.de/minecraft/better_respawn/faq) before submitting a bug report!**

**Bug description**
When player dies multiple times, he will respawn at world spawnpoint instead. 

**Steps to reproduce the issue**
1. Spawn in world
2. Die
3. Die
4. Die
5. Get message like "Your bed or spawn anchor has been obstructed"
6. Get respawned in world spawn point

**Comment by henkelmax** [comment]
This version is no longer maintained/supported, sorry.

**Comment by Proxwian** [comment]
So please let me fix that and do pull request at least

**Comment by henkelmax** [comment]
Sure, go ahead. But there won't be updates for that on modrinth and curseforge.

**Comment by Proxwian** [comment]
You are monster

**Comment by henkelmax** [comment]
> You are monster

?

**Comment by Proxwian** [comment]
I just needed it for my modpack update
