### ISSUE TITLE
Stuck on respawn menu, when i click anything it turns my cursor into a magnifying glass then if i click anywhere again it says my program isnt responding and i have no option but to close.

### ISSUE THREAD

**Issue by RichPrune** [henkelmax/better-respawn#11]
**Please read the [FAQ](https://modrepo.de/minecraft/better_respawn/faq) before submitting a bug report!**

**Bug description**
What the title said,
I love this mod to death and ive used it many a death before just fine. However this death for some reason left me in a softlocked state explained above. Ive restarted the world three times resetting the config and am now gonna try it with the mod uninstalled.

**Steps to reproduce the issue**
1. Go to your world
2. Die
3. You are stuck

**Expected behavior**
Let me click the respawn button
**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.18.2
- Forge version
- Mod version latest

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
idk how to give a mod list, i have 200 but i havent had issues with any other mod today and no other mods screw around with respawning this only happens with this mod

**Screenshots (Optional)**
Screenshots of the issue.
[latest.log](https://github.com/henkelmax/better-respawn/files/10422315/latest.log)

pls lmk if this link works

**Comment by henkelmax** [comment]
This version is no longer supported. Only version 2.x.x of the mod are under active development, sorry.

**Comment by RichPrune** [comment]
can you at least point me to someone who can help cuz my world is corrupted

**Comment by RichPrune** [comment]
plus this was last updated on december 8th???? why is it not being developed

**Comment by henkelmax** [comment]
> can you at least point me to someone who can help cuz my world is corrupted

Maybe uninstalling the mod will get rid of the issue?

**Comment by RichPrune** [comment]
i tried, it didnt work

**Comment by henkelmax** [comment]
> plus this was last updated on december 8th???? why is it not being developed

![image](https://user-images.githubusercontent.com/13237524/212740452-3d173403-a7f5-41ff-bc1e-b7b85fa537db.png)

This is the latest 1.18.2 version.

**Comment by RichPrune** [comment]
![image](https://user-images.githubusercontent.com/103792572/212740625-6b34302d-7b05-4f55-84a4-b212c302a5ab.png)
this is the version im using

**Comment by henkelmax** [comment]
Yes, thats this exact version.

**Comment by RichPrune** [comment]
nvm it was the undefeatables mod my bad
