### ISSUE TITLE
respawn at bed/anchor or near death location options

### ISSUE THREAD

**Issue by slovinsqui** [henkelmax/better-respawn#15]
**Is your feature request related to a problem? Please describe.**
Not really a problem but it would be nice to have the option to respawn at bed/anchor when dying or near the death location

**Describe the solution you'd like**
instead of the quit game/respawn option, let the player choose how to spawn, in their last checkpoint or near death location

**Comment by henkelmax** [comment]
You already respawn at your bed/anchor if you die in a certain range of it.
