### ISSUE TITLE
crash when enter the escape menu

### ISSUE THREAD

**Issue by merasmus44** [henkelmax/better-respawn#18]
I'm not sure if this is an issue with better respawn or server pause
**Bug description**
Game crashes when going to the escape menu

**Steps to reproduce the issue**
1. start minecraft
2. open world
3. press 'esc' or get to the escape menu in any way
4. crash

**Expected behavior**
I should be able to enter the escape menu without crashing
**Log files**
log file [log](https://gist.github.com/merasmus44/fec0cb58f40a3338b28f8db3667975c9#file-latest-log)
crash log file [log](https://gist.github.com/merasmus44/c9b2f075ba3667892b599c3a0d8dd475#file-crash-2023-06-13_15-34-26-server-txt).

**Versions**
- Minecraft version : 1.19
- Fabric version: fabric-loader-0.14.18-1.19
- Mod version: 1.19-2.0.0

**Other mods**
completeconfig 2.0.0
modmenu 4.0.4
serverpause 1.1.0

**Comment by merasmus44** [comment]
nvm it was an issue with server pause

**Comment by ByronChen12138** [comment]
> nvm it was an issue with server pause

Hi! I am facing the same problem now. Could I ask how did you solve this problem?

**Comment by merasmus44** [comment]
I had an incompatible version of better respawn, so I just updated it. Though I am using 1.20.1 minecraft now, so It might not apply there.
