### ISSUE TITLE
is it possible for you to make it so the "respawn nearby" feature works in dimensions other than the overworld as well? 

### ISSUE THREAD

**Issue by kuba26038** [henkelmax/better-respawn#20]
**Is your feature request related to a problem? Please describe.**
my modpack has the ultimate spawn mod installed on it. i used this mod to spawn players within a void dimension from which they can travel to random coordinates. if your mod would work in other dimensions it'd be impossible for players to return to the void dimension, which i'd really like.

**Describe the solution you'd like**
make respawning inside of other dimensions possible

**Comment by henkelmax** [comment]
It would be impossible for the mod to find a valid respawn point in a void world.
