### ISSUE TITLE
Better Respawn 1.19-2.0.0 Makes MC Crash

### ISSUE THREAD

**Issue by ByronChen12138** [henkelmax/better-respawn#21]
**Bug description**
Game crashes when running for some time or going to the escape menu.
As described in [Issue 18](https://github.com/henkelmax/better-respawn/issues/18), the poster said the problem could be the server pause, but I tried to remove the mod, but the same problem still popped out.
""net.minecraft.class_5321.method_29177()" because "this.respawnDimension" is null"

**Steps to reproduce the issue**
1. start Minecraft
2. open world
3. press 'ESC' or get to the escape menu in any way
4. crash

**Expected behavior**
I should be able to enter the escape menu without crashing

**Log files**
Here is the [log](https://gist.github.com/ByronChen12138/58bf314d2744711761222e5609e0ecab) with all the mods installed
Here is the [log ](https://gist.github.com/ByronChen12138/cca6bcbff202093259acb36c909eeeb3)with all the mods installed except the "Multiplayer-Server-Pause-1.19-Fabric-1.1.0"

**Versions**
- Minecraft version: 1.19
- Fabric version: fabric-loader-0.14.18-1.19
- Mod version: better-respawn-fabric-1.19-2.0.0

**Other mods**
completeconfig-2.0.0
fabric-api-0.58.0+1.19
modmenu-4.0.4
Multiplayer-Server-Pause-1.19-Fabric-1.1.0

**Comment by henkelmax** [comment]
1.19 is no longer supported. If this is still happening on newer versions, you can report this issue again.
