### ISSUE TITLE
[Suggestion] Button option for near respawn vs regular respawn

### ISSUE THREAD

**Issue by MrKashew** [henkelmax/better-respawn#22]
This mod is lovely! There are times in which the player would prefer to spawn at world spawn instead. Thoughts on an approach similar to this (except it being a `spawn near` type option)?

![image](https://github.com/henkelmax/better-respawn/assets/53996665/8fa5ecee-a1cb-49d2-84e2-05bd6e86c66a)
(taken from https://www.curseforge.com/minecraft/mc-mods/herespawn)

**Comment by henkelmax** [comment]
As stated in the mod description. This is a server side mod.
Besides this, I wouldn't copy stuff from another mod. Just use that mod if you want that feature.
