### ISSUE TITLE
Respawning fails at maximum radius

### ISSUE THREAD

**Issue by ThreeProphets** [henkelmax/better-respawn#26]
### Bug description

If you set the spawn radius to a value high enough to target a chunk that has not yet been generated, the respawn button will do nothing. My intention is to respawn in a location where it's functionally impossible to locate where I died, similar to Project Zomboid, and presumably the opposite of how the mod is intended to be used. I think you need to give the mod permission to generate terrain or something

### Minecraft version

1.16.5

### Mod version

1.16.5-1.0.0b

### Mod loader and version

Forge 36.2.34

### Steps to reproduce

1. Set `min_respawn_distance` to 2048, the stated maximum 2. Start a new world 3. Die 4. Click "respawn"

### Expected behavior

Respawn at least 2048m away

### Log files

https://gist.github.com/ThreeProphets/348531729b79a7cca9e745f5d8d47619

### Screenshots

https://github.com/user-attachments/assets/8f412193-a3d4-49cd-a13c-465910de7140

**Comment by henkelmax** [comment]
1.16.5 is not supported anymore.
