### ISSUE TITLE
Spawned at spawn point instead

### ISSUE THREAD

**Issue by 1724229** [henkelmax/better-respawn#3]
**Please read the [FAQ](https://modrepo.de/minecraft/better_respawn/faq) before submitting a bug report!**

Read

**Bug description**

I simply died to a siren and some piranha while dismounting a boat and instead of respawning within the respawn radius set, I respawned at spawn point 7k+ blocks away

**Steps to reproduce the issue**
1. Get lured by a siren
2. Get smacked to death by piranhas
3. Press respawn button on death screen

**Expected behavior**

Respawn within set radius.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.16.4
- Forge version: 35.1.29
- Mod version: 1.16.4-1.0.3

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

Optifine
Xearo's Minimap
Xaero's World Map
Reap Mod
Traveller's Backpack
Black Dog's Modpack
Mekanism v10
JEI
Easy Villagers
Easy Piglins
Tiny Mob Farm
Swords of the End
U Team Core
Useful Backpack
Solar Helmet
Bookshelf
WAWLA
Survival Plus
Survival Plus Lightsaber
Lighting Wand
Patchouli
Psi
Inventory Tweaks Revamped
HWHYLA
More Overlays Updated
Crafting Automat
The undefeatables
Spatial Harvester
Harvest with dispenser
Openblocks elevator
jet boots
simply light
extended lights
sweet concrete
iron chest
citadel
ice and fire dragons
inventory pets
toro health damage indicator
mutant beasts
dungeon mod
alex's mobs
guard villager
dungeon mobs
animalism
wyrmroost
exotic birds
better respawn

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please fill out the complete bug template. You are missing log files.

**Comment by 1724229** [comment]
Can't seem to make the gist thingie.
But I figured out how to recreate it everytime.
If you get attracted by the sirens from the ice and fire mod, and die to them better respawn stops working and you go back to spawn point. Sorry can't give the log files not sure why. But I hope this info helps

**Comment by henkelmax** [comment]
No. I need the logs in order to help you.

**Comment by 1724229** [comment]
Ah, then can't do anything about it I guess. Thanks for you time though! Hopefully another user can also open an issue and provide a log file since I can't seem to do it.

**Comment by Proxwian** [comment]
There's can't be any logs here. Mod simply can't find respawn location and then spawn in default location instead of defined radius. You can easily reproduce this by dying multiple times at once and then mod breaks.
