### ISSUE TITLE
Respawn behaviour based on worldspawn if no spawn point is set.

### ISSUE THREAD

**Issue by sanedsf** [henkelmax/better-respawn#6]
**Is your feature request related to a problem? Please describe.**
I would like to use the [spawnRadius](https://minecraft.fandom.com/wiki/Spawn/Multiplayer_details) gamerule from minecraft but that also protects the area and needs OP for breaking blocks etc. So instead I am proposing the following in order to circumvent that behavior but still have the effect.

**Describe the solution you'd like**
Basically there are 2 features that would make sense. If the player does not have a spawn point set (bed/anchor/etc) then:

1. The player is spawned some amount of blocks from the **world spawn**. ex. 2000 blocks (Picture with orange)
2. The player can spawn inside a box/circle, what have you, strip **around** world spawn. So that he is far away from world spawn and possibly their base. (Picture with red)

These options should be configurable. This means that a pack creator can choose which mode his pack needs.

**Describe alternatives you've considered**
There are no alternatives to what I am suggesting.

**Additional context**
Losing your base and most of your stuff because you died is the worst feeling (and probably the player's own fault) which would make perfect sense for a truly hardcore pack.
From the pictures below the world spawn is in the middle (red star).

This orange outline is the no.1 suggested feature
![spawnradiusall](https://user-images.githubusercontent.com/3881715/115976622-7d31b400-a578-11eb-946c-3616769ea690.png)

This red outline is the no.2 suggested feature, the box/circle strip that dictates the spawn radius from the world spawn.
![spawnradiusstrip](https://user-images.githubusercontent.com/3881715/115976620-7b67f080-a578-11eb-8c84-8f18e38a74d5.png)

Thank you for reading this through.

**Comment by henkelmax** [comment]
This defeats the whole purpose of this mod.
This mod is solely made to respawn near your death location.
