### ISSUE TITLE
Game stuck on loading terrain after entering end portal

### ISSUE THREAD

**Issue by Nauviax** [henkelmax/better-respawn#7]
**Bug description**
Game stuck on loading terrain after entering an end portal.
Specifically, after skipping the credits, my character was still in the end, but unable to enter the portal. (Jumping around and not interacting with the portal block) I did not try to interact with a crafting table or my inventory and just reloaded the game.
Upon reloading, the game managed to load the world (Got to 100%) and froze on loading terrain. This happened every time.
Uninstalling the mod fixed the problem. However, I loaded in at the world spawn, and not my bed spawn point.

**Steps to reproduce the issue**
Could not reproduce, as I had to uninstall the mod to fix the game freezing on load.

**Expected behavior**
I would load in at my spawn point, at a bed just outside the end fortress.

**Log files**
[latest.log](https://github.com/henkelmax/better-respawn/files/7481781/latest.log)
The file is 90% the same line repeated multiple times a second:
    [Render thread/WARN]: Unknown custom packet identifier: better_respawn:default
This repeats forever until I forcibly closed the game. No alt + f4, pressing the x was enough to end it.

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.0
- Mod version 1.16.5-1.0.0

**Other mods**
Nothing that should conflict with respawning mechanics.
Mekanism, Psi, Quark and Inventory Pets to name a few of which I had items in my inventory from.

**Comment by henkelmax** [comment]
Should be fixed in 2.0.0
But 1.16.5 won't get any updates anymore, sorry.
