### ISSUE TITLE
nether respawn

### ISSUE THREAD

**Issue by Andrezinho1** [henkelmax/better-respawn#9]
**Please read the [FAQ](https://modrepo.de/minecraft/better_respawn/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
1. go to nether
2. die
3. respawn at world spawn

**Expected behavior**
respawn in bed

**Log files**
no crash log

**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.80
- Mod version 1.0

**Other mods**
several none that should interfere

**Comment by henkelmax** [comment]
This mod version is outdated. Only version 2.x.x will receive updates.
